### ISSUE TITLE
LFS: missing line feed after message

### ISSUE THREAD

**Issue by aymanbagabas** [bk2204/scutiger#11]
Hi @bk2204,

I've been working on a pure-SSH implementation and following scutiger-lfs and the specs. I noticed that scutiger-lfs does not add a line feed LF after error messages. The specs describe `error-message = *PKT-LINE(data LF)` however, scutiger-lfs doesn't add a LF after messages. I've also noticed some inconsistencies in the proposal https://github.com/git-lfs/git-lfs/pull/5560

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I've got #13 up to fix that and I'll plan to do a release this weekend assuming I haven't broken the Git LFS testsuite, which I'll check tomorrow.

**Comment by aymanbagabas** [comment]
> Hey,
> 
> Thanks for the report.  I've got #13 up to fix that and I'll plan to do a release this weekend assuming I haven't broken the Git LFS testsuite, which I'll check tomorrow.

Welp, I didn't see that one. Thanks for the quick response, I will close this one 🙂
